### ISSUE TITLE
Bug: 2026.0.2 critically breaks with empty configuration

### ISSUE THREAD

**Issue by MattTheCuber** [FHPythonUtils/LicenseCheck#147]
On version >=2026.0.2, the CLI parsing is broken and throws the error: `TypeError: LC_Config.__init__() missing 6 required positional arguments:`

Specifically, it seems to have been introduced in https://github.com/FHPythonUtils/LicenseCheck/commit/e60c24d8fe8e874819d8183ecb351b6fb36a2d41

### MRE Example

New project with a single file, `pyproject.toml`:

```toml
[project]
name = "test"
license = "MIT"
version = "0.1.0"
dependencies = ["numpy"]
```

<img width="1314" height="1016" alt="Image" src="https://github.com/user-attachments/assets/70e0795d-b10d-49b0-8e12-8da8b0472a76" />

**Comment by joanise** [comment]
We faced this issue in our project.

This minimal fix solves the problem on my local PC:

```
diff --git a/licensecheck/models/config.py b/licensecheck/models/config.py
index ea65e7719e..092f4ffd8a 100644
--- a/licensecheck/models/config.py
+++ b/licensecheck/models/config.py
@@ -8,12 +8,12 @@ from typing import Any
 class LC_Config:
        """LC_Config type."""

-       file: str | None
-       license: str | None
-       format: str | None
-       pypi_api: str | None
-       show_only_failing: bool
-       zero: bool
+       file: str | None = field(default=None)
+       license: str | None = field(default=None)
+       format: str | None = field(default=None)
+       pypi_api: str | None = field(default=None)
+       show_only_failing: bool = field(default=False)
+       zero: bool = field(default=False)

        requirements_paths: set[str] = field(default_factory=set)
        groups: set[str] = field(default_factory=set)
```

If those six fields don't get a value passed in, the call to the `LC_Config` contructor fails as you saw.

I didn't have time to submit a PR, or to fully analyse if this solution would have unintended side effects, but it is sufficient for licensecheck to work correctly on our projects.

**Comment by FredHappyface** [comment]
Thanks for this, 2026.0.4 will use a pydantic model to represent the config so hopefully this sort of error should be less likely in the future. Just fixed this :)
